// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qklipfmmzdfqafybkwbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrbGlwZm1temRmcWFmeWJrd2JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMjYzNzYsImV4cCI6MjA2MzgwMjM3Nn0.CS3B07l1ELoAdAoKV2RnFLwqe6v-_-pz3z-8ki_BRro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);